import { Source_Serif_4 } from "next/font/google";
import "./globals.css";

const serif = Source_Serif_4({ subsets: ["latin"] });

export const metadata = {
  title: "LakeWood Haven Kindergarten",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={serif.className}>{children}</body>
    </html>
  );
}
